/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/AboutSection.vue')['default']
    ArticleSection: typeof import('./src/components/ArticleSection.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BlogPostCard: typeof import('./src/components/cards/BlogPostCard.vue')['default']
    Button: typeof import('primevue/button')['default']
    FooterSection: typeof import('./src/components/sections/FooterSection.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    GetInTouchSection: typeof import('./src/components/GetInTouchSection.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    NavbarSection: typeof import('./src/components/sections/NavbarSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestimonialSection: typeof import('./src/components/TestimonialSection.vue')['default']
    WorkExperienceSection: typeof import('./src/components/WorkExperienceSection.vue')['default']
  }
}
