/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMeSection: typeof import('./src/components/sections/AboutMeSection.vue')['default']
    AboutSection: typeof import('./src/components/sections/AboutSection.vue')['default']
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    ArticleSection: typeof import('./src/components/sections/ArticleSection.vue')['default']
    AutoscrollGallery: typeof import('./src/components/gallery/AutoscrollGallery.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BlogPostCard: typeof import('./src/components/cards/BlogPostCard.vue')['default']
    Button: typeof import('primevue/button')['default']
    Carousel: typeof import('primevue/carousel')['default']
    FaqsSection: typeof import('./src/components/sections/FaqsSection.vue')['default']
    FooterSection: typeof import('./src/components/sections/FooterSection.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    GetInTouchSection: typeof import('./src/components/GetInTouchSection.vue')['default']
    HeroSection: typeof import('./src/components/sections/HeroSection.vue')['default']
    LatestArticleCard: typeof import('./src/components/cards/LatestArticleCard.vue')['default']
    LatestArticlesSection: typeof import('./src/components/sections/LatestArticlesSection.vue')['default']
    NavbarSection: typeof import('./src/components/sections/NavbarSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TestimonialSection: typeof import('./src/components/sections/TestimonialSection.vue')['default']
    TestimonialsSection: typeof import('./src/components/sections/TestimonialsSection.vue')['default']
    WorkExperienceSection: typeof import('./src/components/sections/WorkExperienceSection.vue')['default']
  }
}
